name: pokolenie_vpn
description: Android VPN-клиент «Поколение» с автообновляемым каталогом и честным URL Test.
publish_to: none
version: 0.9.4+94

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5
  http: 1.5.0
  shared_preferences: 2.5.3
  crypto: 3.0.6
  uuid: 4.5.1
  file_selector: 1.1.0
  singbox_mm: 0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/warp/
    - catalog/public_catalog.json
    - catalog/sources.json
